- name: Delete old account from the previous cohort
  hosts: all
  become: yes

  tasks:
    - name: Logout the user
      ansible.builtin.shell: |
        pkill -KILL -u {{ user_to_delete }}
      ignore_errors: yes

    - name: Delete user. If it fails, then it means the user is successfully deleted
      become: yes
      become_user: root
      ignore_errors: yes
      ansible.builtin.user:
        name: "{{ user_to_delete }}"
        state: absent
        remove: yes
        force: yes
