- name: Create directory for reset-utils
  become: yes
  become_user: "{{ new_user }}"
  ansible.builtin.file:
    path: "/home/{{ new_user }}/reset-utils"
    state: directory
    group: "{{ new_user }}"
    owner: "{{ new_user }}"
    mode: 0755
    state: directory

- name: Copy chrome.js to remote host
  become: yes
  become_user: "{{ new_user }}"
  ansible.builtin.copy:
    src: tasks/chrome.js
    # this js can be found in the same directory as this playbook
    # it's used to create pinned bookmarks
    # this js file should run in the second playbook
    dest: "/home/{{ new_user }}/reset-utils/chrome.js"
    group: "{{ new_user }}"
    owner: "{{ new_user }}"
    mode: 0644

- name: Close/kill Chromium
  become: yes
  become_user: "{{ new_user }}"
  become: yes
  ansible.builtin.shell: |
    pkill chrome
  args:
    executable: /bin/bash
  ignore_errors: yes
     
# - name: Reset Chromium history, cache and cookies
#   become: yes
#   become_user: "{{ new_user }}"
#   ansible.builtin.shell: |
#     rm -rf "/home/{{ new_user }}/snap/chromium/common/chromium/"
#   args:
#     executable: /bin/bash
