- name: Delete contents of specified directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
  loop:
    - Pictures
    - Videos
    - Music
    - Documents
    - Downloads
    - Desktop
    - workspace

- name: Recreate empty directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - Pictures
    - Videos
    - Music
    - Documents
    - Downloads
    - Desktop
    - workspace
