- name: Set the app favourites in the dock
  become: yes
  become_user: "{{ new_user }}"
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['firefox_firefox.desktop', 'chromium_chromium.desktop', 'code.desktop', 'org.gnome.Terminal.desktop']"
    state: present

- name: Position the dock to be on the left
  become: yes
  become_user: "{{ new_user }}"
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'LEFT'"
    state: present
