- name: Install updates
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: Update snap packages
  ignore_errors: yes
  ansible.builtin.shell: |
    sudo snap refresh
  args:
    executable: /bin/bash
  become: yes

- name: Install OS updates
  ansible.builtin.shell: |
    sudo apt-get update
    sudo apt-get upgrade -y
  args:
    executable: /bin/bash
  become: yes
