- name: Create .ssh directory
  file:
    path: "/home/{{ user }}/.ssh"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

- name: Copy public key
  ansible.builtin.copy:
    src: ssh-keys/id_gh_daa.pub
    dest: "/home/{{ user }}/.ssh/id_gh_daa.pub"
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0644

- name: Copy private key
  ansible.builtin.copy:
    src: ssh-keys/id_gh_daa
    dest: "/home/{{ user }}/.ssh/id_gh_daa"
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0600

- name: Start ssh-agent
  become: yes
  become_user: "{{ user }}"
  shell: eval $(ssh-agent -s) && echo $SSH_AUTH_SOCK
  register: ssh_auth_sock

- name: Add ssh key
  expect:
    command: ssh-add /home/{{ user }}/.ssh/id_gh_daa
    responses:
      "Enter passphrase": "{{ git_iam_passphrase }}"
  environment:
    SSH_AUTH_SOCK: "{{ ssh_auth_sock.stdout_lines[1] }}"

- name: Create workspace directory
  file:
    path: "/home/{{ user }}/workspace"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775
