- name: Create .ssh directory
  file:
    path: "/home/{{ new_user }}/.ssh"
    state: directory
    owner: "{{ new_user }}"
    group: "{{ new_user }}"
    mode: 0700

- name: Copy public key
  ansible.builtin.copy:
    src: ssh-keys/id_gh_daa.pub
    dest: "/home/{{ new_user }}/.ssh/id_gh_daa.pub"
    group: "{{ new_user }}"
    owner: "{{ new_user }}"
    mode: 0644

- name: Copy private key
  ansible.builtin.copy:
    src: ssh-keys/id_gh_daa
    dest: "/home/{{ new_user }}/.ssh/id_gh_daa"
    group: "{{ new_user }}"
    owner: "{{ new_user }}"
    mode: 0600

- name: Start ssh-agent
  become: yes
  become_user: "{{ new_user }}"
  shell: eval $(ssh-agent -s) && echo $SSH_AUTH_SOCK
  register: ssh_auth_sock

- name: Add ssh key
  expect:
    command: ssh-add /home/{{ new_user }}/.ssh/id_gh_daa
    responses:
      "Enter passphrase": "{{ git_iam_passphrase }}"
  environment:
    SSH_AUTH_SOCK: "{{ ssh_auth_sock.stdout_lines[1] }}"

- name: Create workspace directory
  file:
    path: "/home/{{ new_user }}/workspace"
    state: directory
    owner: "{{ new_user }}"
    group: "{{ new_user }}"
    mode: 0775

- name: Setup git iam
  become: yes
  become_user: "{{ new_user }}"
  ansible.builtin.shell: |
    export NVM_DIR="/home/{{ new_user }}/.nvm"
    . "/home/{{ new_user }}/.nvm/nvm.sh"
    git-iam --init {{ git_iam_url }} --on-campus
  args:
    chdir: "/home/{{ new_user }}/workspace/test"
